export const voices = [
  { label: "Zeina (Arabic, Female)", value: "Zeina" },
  { label: "Zhiyu (Chinese Mandarin, Female)", value: "Zhiyu" },
  { label: "Naja (Danish, Female)", value: "Naja" },
  { label: "Mads (Danish, Male)", value: "Mads" },
  { label: "Lotte (Dutch, Female)", value: "Lotte" },
  { label: "Ruben (Dutch, Male)", value: "Ruben" },
  { label: "Nicole (English Australian, Female)", value: "Nicole" },
  { label: "Russell (English Australian, Male)", value: "Russell" },
  { label: "Amy (English British, Female)", value: "Amy" },
  { label: "Emma (English British, Female)", value: "Emma" },
  { label: "Brian (English British, Male)", value: "Brian" },
  { label: "Aditi (English Indian, Female)", value: "Aditi" },
  { label: "Raveena (English Indian, Female)", value: "Raveena" },
  { label: "Ivy (English US, Female child)", value: "Ivy" },
  { label: "Joanna (English US, Female)", value: "Joanna" },
  { label: "Kendra (English US, Female)", value: "Kendra" },
  { label: "Kimberly (English US, Female)", value: "Kimberly" },
  { label: "Salli (English US, Female)", value: "Salli" },
  { label: "Joey (English US, Male)", value: "Joey" },
  { label: "Kevin (English US, Male child)", value: "Kevin" },
  { label: "Geraint (English Welsh, Male)", value: "Geraint" },
  { label: "Céline (French, Female)", value: "Celine" },
  { label: "Léa (French, Female)", value: "Lea" },
  { label: "Mathieu (French, Male)", value: "Mathieu" },
  { label: "Chantal (French Canadian, Female)", value: "Chantal" },
  { label: "Marlene (German, Female)", value: "Marlene" },
  { label: "Vicki (German, Female)", value: "Vicki" },
  { label: "Hans (German, Male)", value: "Hans" },
  { label: "Aditi (Hindi, Female)", value: "Aditi" },
  { label: "Dóra (Icelandic, Female)", value: "Dora" },
  { label: "Karl (Icelandic, Male)", value: "Karl" },
  { label: "Carla (Italian, Female)", value: "Carla" },
  { label: "Bianca (Italian, Female)", value: "Bianca" },
  { label: "Giorgio (Italian, Male)", value: "Giorgio" },
  { label: "Mizuki (Japanese, Female)", value: "Mizuki" },
  { label: "Takumi (Japanese, Male)", value: "Takumi" },
  { label: "Seoyeon (Korean, Female)", value: "Seoyeon" },
  { label: "Liv (Norwegian, Female)", value: "Liv" },
  { label: "Ewa (Polish, Female)", value: "Ewa" },
  { label: "Maja (Polish, Female)", value: "Maja" },
  { label: "Jacek (Polish, Male)", value: "Jacek" },
  { label: "Jan (Polish, Male)", value: "Jan" },
  { label: "Camila (Portuguese Brazilian, Female)", value: "Camila" },
  { label: "Vitória (Portuguese Brazilian, Female)", value: "Vitoria" },
  { label: "Ricardo (Portuguese Brazilian, Male)", value: "Ricardo" },
  { label: "Inês (Portuguese European, Female)", value: "Ines" },
  { label: "Cristiano (Portuguese European, Male)", value: "Cristiano" },
  { label: "Carmen (Romanian, Female)", value: "Carmen" },
  { label: "Tatyana (Russian, Female)", value: "Tatyana" },
  { label: "Maxim (Russian, Male)", value: "Maxim" },
  { label: "Conchita (Spanish European, Female)", value: "Conchita" },
  { label: "Lucia (Spanish European, Female)", value: "Lucia" },
  { label: "Enrique (Spanish European, Male)", value: "Enrique" },
  { label: "Mia (Spanish Mexican, Female)", value: "Mia" },
  { label: "Lupe (Spanish US, Female)", value: "Lupe" },
  { label: "Penélope (Spanish US, Female)", value: "Penelope" },
  { label: "Miguel (Spanish US, Male)", value: "Miguel" },
  { label: "Astrid (Swedish, Female)", value: "Astrid" },
  { label: "Filiz (Turkish, Female)", value: "Filiz" },
  { label: "Gwyneth (Welsh, Female)", value: "Gwyneth" },
] as const;

export type Voices = typeof voices;
